spring:
  datasource:
    url: jdbc:h2:mem:job_event_storage
    driver-class-name: org.h2.Driver
    username: sa
    password:

elastic-job:
  reg:
    type: zookeeper
    zookeeper:
      id: regCenter
      server-lists: localhost:2181
      namespace: elastic-job-lite-springboot

  job:
    simple:
      - id: springBootSimpleJob
        class: io.wangxin.elasticjob.example.jobs.job.simple.SpringBootSimpleJob
        registry-center-ref: regCenter
        cron: 0/5 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
        monitor—execution: false
        failover: true
        description: 只运行一次的作业示例
        disabled: false
        overwrite: true
        monitor-port: 9888

      - id: springBootSimpleJobTwo
        class: io.wangxin.elasticjob.example.jobs.job.simple.SpringBootSimpleJobTwo
        registry-center-ref: regCenter
        cron: 0/5 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
        monitor—execution: false
        failover: true
        description: 只运行一次的作业示例2
        disabled: false
        overwrite: true
        monitor-port: 9888

    dataflow:
      - id: springBootDataflowJob
        class: io.wangxin.elasticjob.example.jobs.job.dataflow.SpringBootDataflowJob
        registry-center-ref: regCenter
        cron: 0/5 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
        max-time-diff-seconds: -1
        monitor-execution: true
        failover: true
        streaming-process: true
        description: 按顺序不停止运行的作业示例
        disabled: false
        overwrite: true

    script:
      - id: springScriptJob
        registry-center-ref: regCenter
        cron: 0/5 * * * * ?
        description: shell脚本执行测试
        script-command-line: your_path/elastic-job-spring-boot-project/elastic-job-spring-boot-samples/elastic-job-spring-boot-samples-jobs/src/main/resources/script/demo.sh
